import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function TopNav() {
  return(
    <nav className="w-full flex items-center justify-between">
      <p>Cat.jpg</p>
      <p>user</p>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <TopNav/>
        {children}
      </body>
    </html>
  );
}
